<script>
	// logic goes here
</script>

<div>
    <h1>Lab 10c</h1>
    <section>
        <h2>Setup</h2>
        <p>
            To install the svelte framework, I first had to ensure that npm, a package
            manager for the node js runtime environment, was installed. Since my development machine 
            is a mac, I used homebrew to install node via the command 'brew install node'. To install 
            svelte, I ran the command: 'npm create svelte@latest lab10c'. I was then taken through a 
            set of prompts in the terminal such as whether or not to create my app using typescript,
            what build tool to use, etc. To build the page, I went to the routes folder that was
            generated by the previous script, and then coded from the '+page.svelte' file, which
            is the page for the base route of the app.
        </p>
    </section>
    
    <section>
        <h2>Challenges</h2>
        <p>
            I've used many web-frameworks in the past for personal and company projects, so the overall
            process of learning how to use svelte was fairly straightforward. One small difficulty I faced
            however, was getting used to the folder structure of the framework as well as figuring out the
            entrypoint to the application. I was able to remediate this problem by tracing through
            all the files, figuring out what the purpose of each one was, and then consulting the
            <a href="https://svelte.dev/docs/basic-markup">documentation</a> whenever I was unsure on a 
            particular file or component.
        </p>
    </section>

</div>

<style>
    * { 
        font-family: Raleway; 
    }

	div {
        display: flex;
        flex-direction: column;
        align-items: center;
        max-width: 1000px;
        box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
        border-radius: 20px;
        margin-left: auto;
        margin-right: auto;
        padding-bottom: 100px;
        margin-top: 25px;
    }
    
    section {
        width: 60%;
    }

    a { 
        text-decoration: none; 
    }

</style>